variable "acm_region" {}
variable "acm_verification_record_name" {}
variable "acm_verification_record_value" {}
variable "bucket_name" {}
variable "cloudfront_origin_id" {}
variable "domain" {}
variable "environment" {}
variable "fqdn" {}
variable "host" {}
